[General]
accent_color=#C06C84
background_color=#000000
block_steam_updates=true
create_application_shortcuts=false
effects_volume=5
font=TrixieCyrG-Plain
font-file=
font-size=10
font-style=Normal
generate_achievements=true
gif_display_enabled=true
hum_volume=0
ignore_color_warnings=false
library_mode=true
master_volume=0
morrenus_api_key=smm_a88fbfde7ff1d0ad0d794beed441efa40de255fff1e748a18b099f1e6a1f02b6e024832cbd2251dd61685d316e51446b
play_50hz_hum=false
play_etw=false
play_lall=false
prompt_steam_restart=true
sgdb_api_key=4a315e6f0ed21c00869bf7e834839605
sls_config_management=true
slssteam_mode=true
titlebar_position=bottom
ui_mode=default
use_steamless=true
